apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: shaharweiss1234/node-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "250"
        ports:
        - containerPort: 3000
